### ISSUE TITLE
Default password set for console

### ISSUE THREAD

**Issue by liamgr** [online-labs/image-archlinux#7]
Using the latest image you can login via the console using root / root.

From the docs I understood that you shouldn't be able to login without creating user accounts.

(Image is: distrib-archlinux-latest-2015-02-09_17:37-snapshot)

**Comment by moul** [comment]
Wow, this is probably due to the image we are inheriting for creating this image,
I will give a check and ensure root password is not 'root' :)

I will also write a unit test to ensure it does not happen anymore in the future

Thanks a lot

**Comment by moul** [comment]
Fixed with: 71d1ba427f8d186f0174ce732243fff0d138c0ae

We will wait to get more new improvements before releasing a new image, but if you want to remove the root password on a running instance, just type the following command:

    $ passwd -d root

Is everything ok for you ? thanks again for reporting

**Comment by aimxhaisse** [comment]
Note that the SSH authentication via password is disabled, the only way this can be used is via the console.

**Comment by moul** [comment]
You're right, I just added a test to ensure `/etc/ssh/sshd_config` contains `PermitRootLogin without-password`

**Comment by junglhilt** [comment]
It would be really helpful if we could verify the ssh_host_key out of band via the api / console / webui - is there a place I could create an issue for this, other than creating an issue on each image?

**Comment by moul** [comment]
@junglhilt we are working on this feature, we want to improve the global security for login, i.e:

- print the `ssh_host_key`s on the console
- being able to generate a random root password on first-boot/demand

We already have an issue in our internal ticketing system, but you can create an issue on https://github.com/scaleway/image-tools/issues for the public follow up, if you do, don't forget to cross-reference this issue :)

Thanks
